### ISSUE TITLE
Error while installing Csv data upload 

### ISSUE THREAD

**Issue by jeevansrivastava** [ankit-arora/clevertap-data-upload#5]
Hello Ankit,
 We are following below document for installing CSV upload 

[](https://developer.clevertap.com/docs/data-imports)

We are facing issue while installing 

cannot find package "github.com/ankit-arora/clevertap-data-upload/globals" in any of:
	/Users/jeevansrivastava/go/src/github.com/CleverTap/clevertap-data-upload/vendor/github.com/ankit-arora/clevertap-data-upload/globals (vendor tree)
	/usr/local/go/src/github.com/ankit-arora/clevertap-data-upload/globals (from $GOROOT)
	/Users/jeevansrivastava/go/src/github.com/ankit-arora/clevertap-data-upload/globals (from $GOPATH)

**Comment by ankit-arora** [comment]
Is the code in your $GOPATH?

**Comment by ankit-arora** [comment]
Also try using go modules.

**Comment by jeevansrivastava** [comment]
Thanks, @ankit-arora able to install it by updating $GOPATH
